name: generate_pihole_cloud

on:
  push:
    paths:
      - 'adguard-allowlist-cloudgaming'
  workflow_dispatch:

jobs:
  convert-cloud:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Convert Cloud-Whitelist to Pi-hole
        run: |
          if [ -f "adguard-allowlist-cloudgaming" ]; then
            sed -e 's/@@||//g' -e 's/\^//g' -e 's/\$important//g' -e '/^!/d' -e '/^#/d' -e '/^$/d' "adguard-allowlist-cloudgaming" > pihole-cloudgaming.txt
          else
            echo "File not found"
            exit 1
          fi
          
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add pihole-cloudgaming.txt
          git commit -m "Update Pi-hole list" || echo "No changes"
          git push
